### ISSUE TITLE
Can we upload it to Maven Central or JCenter

### ISSUE THREAD

**Issue by wuseal** [alirezaarzehgar/kotlin_file#1]
Hi, Very Glad to see you created such a greater library for Kotlin/Native, It looks awesome, also could we upload it to Maven or Jcenter, then I can declare it in Gradle Dependencies, then it is easy for auto-build an executable binary on all platform without the need to install manually.

**Comment by alirezaarzehgar** [comment]
> Hi, Very Glad to see you created such a greater library for Kotlin/Native, It looks awesome, also could we upload it to Maven or Jcenter, then I can declare it in Gradle Dependencies, then it is easy for auto-build an executable binary on all platform without the need to install manually.

hello, it's kind of you
very glad to your comment
i did not know this way :D
i need to read more Kotlin/Native and improve my skills.
we can do this.
your comment is very helpful for me :+1: 
thank you for your idea and comment.
